### ISSUE TITLE
lock aquire times out and restarts caching

### ISSUE THREAD

**Issue by kenodressel** [aeternity/tipping-community-backend#101]
```
Error: async-lock timed out
    at Timeout._onTimeout (/app/node_modules/async-lock/lib/index.js:164:17)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

```

after this every lock.aquire gets logged an additional time

so before this error happens:
```
   cache ae_mainnet:transactionEvent:th_fcPtLxzAvdxynqrZKWAY9YbGRwacnweyRHyJmRzWoEZbEhLt2 723 ms

   lock.acquire ae_mainnet:transactionEvent:th_fcPtLxzAvdxynqrZKWAY9YbGRwacnweyRHyJmRzWoEZbEhLt2 724 ms
```

```
  cache ae_mainnet:transactionEvent:th_fcPtLxzAvdxynqrZKWAY9YbGRwacnweyRHyJmRzWoEZbEhLt2 723 ms

   lock.acquire ae_mainnet:transactionEvent:th_fcPtLxzAvdxynqrZKWAY9YbGRwacnweyRHyJmRzWoEZbEhLt2 724 ms

   lock.acquire ae_mainnet:transactionEvent:th_fcPtLxzAvdxynqrZKWAY9YbGRwacnweyRHyJmRzWoEZbEhLt2 720 ms
```

and again, after each error, it happens once more

**Comment by thepiwo** [comment]
introducing another lock for keepHot will avoid multiple keep hot runs, mitigating the problem probably

**Comment by thepiwo** [comment]
I did investigate the code and `Error: async-lock timed out` is expected behaviour here, when we don't have the contract events ready we want to not block the lock on regeneration generally.

For "keepHot" I'll add a single non timeouting lock to mitigate the problem completely.

This will also be vastly improved with the new MDW usage.
